### ISSUE TITLE
Is 'mapping' always required for textures?

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#16]
The top of the textures page states that "A texture requires, at the minimum, a url path and a mapping mode":

https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/textures.md#textures

However the subsequent paragraph on the 'mapping' parameter calls it an "optional" string:

https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/textures.md#mapping

It's also a bit confusing that the syntax for textures differs slightly between the top-level textures element and "inline" in a material, but I believe that's an actual quirk of the library and not a documentation problem.

**Comment by bcamper** [comment]
@patriciogonzalezvivo I think there is a default mapping?

**Comment by meetar** [comment]
According to @patriciogonzalezvivo, the default is "spheremap", and for normal mapping is "triplanar" - queued for fixing

**Comment by meetar** [comment]
Fixed by https://github.com/tangrams/tangram-docs/commit/fa68da1b23805f522fbfe96323706e9b00e29cdb

**Comment by bcamper** [comment]
Is greater elaboration perhaps needed to properly explain the difference
between textures, which are distinct entities, and materials, which can
reference one or more of those textures through ambient, diffuse, etc
properties?

For example, 'filtering' is a property of a texture that affects the
appearance of the texture in all instances in which it is displayed, while
'mapping' is a material property setting that describes how a texture is
spatially applied to that specific material property (but the same texture
could have other mappings for other properties on the same material, or in
other materials).

While there's a shortcut to create a texture by specifying a url in a
material property, this is otherwise not a more fully featured 'inline'
texture specification.

**Comment by meetar** [comment]
Hmm, I'm not sure – are there any particular places in the docs where this confusion is most apparent? I hadn't noticed any trouble, but I haven't worked with those docs in a while.
