### ISSUE TITLE
Is text size also quantized?

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/tangram-docs#268]
https://tangrams.readthedocs.io/en/master/Syntax-Reference/yaml/#stops

> At intermediate zoom levels, values will be interpolated linearly, with behavior depending on draw style and parameter. In the above example, at zoom 13, the value will be 4.5m, and at zoom 13.5, the value will be 5.25m. However, for all color values, the values are only be updated when tile geometry is built – typically at whole-number zoom changes.

It appears that text size is also quantized. Both

` text_size: [[15, 12], [16, 13], [17, 15], [18, 17], [19, 24]]`

`text_size: [[15, 12px], [16, 13px], [17, 15px], [18, 17px], [19, 24px]]`

resulted in jumps as zoom level changes

Add also

> The same will happen with text_size.

Is anything else similarly constrained? Should I open PR adding this info? Or is it bug/limitation of a specific renderer backend?

**Comment by bcamper** [comment]
Yes, generally speaking, most of these zoom-stop-based parameters will only be re-evaluated at integer zoom levels, when new tiles are built. The only exceptions I'm thinking of are camera parameters like `focal_length` which can be evaluated continuously (there may be a couple others I'm overlooking, but it is the exception rather than the rule). Please feel free to submit clarifying language!
