### ISSUE TITLE
specify which priority wins - ones with higher or lower number?

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/tangram-docs#269]
For https://github.com/tangrams/tangram-docs/blob/master/docs/Syntax-Reference/layers.md#priority it appears to not be specified.

For https://github.com/tangrams/tangram-docs/blob/master/docs/Syntax-Reference/draw.md#order it is not entirely clear but "In this case, higher-ordered layers will be drawn over lower-ordered layers." indicated that higher values win with lower ones in case of a conflict.

Issue triggered by https://github.com/westnordost/StreetComplete/pull/1930 where I am confused by `order`, `priority` and why noncollide markers collide.

**Comment by matkoniecz** [comment]
Because `10` appears to win with `1` and `0` appears to win with `1` and `1` appears to win with `2`.

**Comment by matteblair** [comment]
Put simply: lower values win for `priority` (`priority: 1` has precedence over `priority: 2`) and higher values win for `order` (`order: 2` has precedence over `order: 1`). There are subtleties though, and the docs should probably clarify a bit more.

> For https://github.com/tangrams/tangram-docs/blob/master/docs/Syntax-Reference/layers.md#priority it appears to not be specified.

There are two distinct parts of the scene configuration named `priority`. One is the property you linked above - this is a property on *layers*. When a feature matches multiple "sibling" layers, the layer `priority` determines the order in which the layers are applied.

The other `priority` is a property on drawn features like labels, and its behavior is described here: https://github.com/tangrams/tangram-docs/blob/master/docs/Syntax-Reference/draw.md#priority

> For https://github.com/tangrams/tangram-docs/blob/master/docs/Syntax-Reference/draw.md#order it is not entirely clear but "In this case, higher-ordered layers will be drawn over lower-ordered layers." indicated that higher values win with lower ones in case of a conflict.

The documentation is worded this way because `order` only affects the drawing order of features that are at the same elevation. If you have a rooftop drawn at 5m elevation with `order: 1` overlapping a road drawn at 0m elevation with `order: 2`, the rooftop will still be drawn on top. If you have two overlapping roads drawn at 0m elevation, the one with the higher `order` will be drawn on top.

Does this help? If these clarifications make sense I can add them to the documentation.

**Comment by matkoniecz** [comment]
> Does this help?

Yes! Though I am unsure how one may handle part about looking at wrong `priority`. Add "you may be looking for $LINK"?

**Comment by matteblair** [comment]
Resolved by https://github.com/tangrams/tangram-docs/pull/271
