### ISSUE TITLE
"extrude" draw parameter not documented

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#39]
I can guess at how this works, but others might not ;)

**Comment by tallytalwar** [comment]
It will also be good to document whats the default behavior for extrude parameter.

**Comment by meetar** [comment]
Fixed with https://github.com/tangrams/tangram-docs/commit/33cf65fff33e14952178b779873667f59047e4c9, thanks!

**Comment by matteblair** [comment]
I just made a small edit to add `boolean` because it's clearly allowed in the examples, but upon reflection I realized that this still needs more information. When a boolean value is specified, the behavior is to extrude between `feature.min_height` and `feature.height`, yes? 

And from [the source](https://github.com/tangrams/tangram/blob/master/src/styles/polygons/polygons.js#L69) it seems that `extrude` can also take a two-element array that becomes the effective `height` and `min_height`. 

If an array value is interpreted as a pair of heights, is it actually possible to use stops for this parameter?

**Comment by bcamper** [comment]
@blair1618's reading is correct. This code is very old, and I've generally tried to avoid defaults that rely on specific feature properties like `height`, since this is supposed to be data agnostic (text style also defaults to feature property `name`, but that seems pretty reasonable). That said, changing it now would cause the styles to become more verbose, which isn't great either. So maybe we just continue to live with it.

Returning an array of two values isn't a super common case, but it's useful for "lifting" something off the ground to a specific height. More of a future dataviz case, but one I had in mind at the start.

**Comment by meetar** [comment]
Yep – refined with https://github.com/tangrams/tangram-docs/commit/4d824e96bc85b074e2b28bb3ac9876f9f4812de5 and https://github.com/tangrams/tangram-docs/commit/1593a3b8cdcb4aa76c51039634f23431666e8e46, thanks again!
