### ISSUE TITLE
Create a linter application to validate scene file

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-docs#62]

**Comment by bcamper** [comment]
This ties in with work @patriciogonzalezvivo and @louh have been discussing. In brief, Tangram Play has an early foundation for a syntax/API doc structure: https://github.com/tangrams/tangram-play/blob/gh-pages/data/tangram-api.json

We've discussed extending this to capture additional information such as required fields, valid values/ranges, descriptive/help text, etc., and using it to both enhance the Play experience, and then extract into a separate module that could serve as a command-line validator, and/or be integrated into Tangram (JS) itself.

**Comment by matteblair** [comment]
Part of me would very much like to make a parser + linter using [ANTLR](http://www.antlr.org), or at least something based on formal grammars.

**Comment by bcamper** [comment]
@blair1618 that could be interesting. My chief concern would be something cross-platform, but it looks like ANTLR can [produce JS code](https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md) so that's interesting.

Another consideration is integration with Play and other tools as described above -- ideally we would describe/document the API once and then be able to use that info in multiple contexts. Perhaps this is still possible with the type of tool you suggest though (I don't have enough experience).

**Comment by karimnaaji** [comment]
For cross-platform concern we could also think of using https://www.gnu.org/software/bison/ which produces c++ parsers, and make an emscripten port of it if we want to go that way.

**Comment by bcamper** [comment]
We should step back and think about what the real-world use cases for this validation is though. Unless run-time validation in Tangram ES is a need (possibly), I'd rather not start with a C++ bias :)

**Comment by tallytalwar** [comment]
With respect to Tangram ES doing a run-time validation, I am not opposing the idea, however tangram-es should mostly be doing a graceful fall-back if a bad scene file is fed to it. I do not think validation should be part of the core tangram-es functionality.

**Comment by pnorman** [comment]
There's an IETF standard for defining a [json schema](http://json-schema.org/) with validators in over a dozen languages. YAML to JSON conversion is lossy, but for the types of scalars a scene file is likely to have this might not be an issue, and you could then use a JSON schema and a JSON schema validator.

I wouldn't lean towards ANTLR, because scene files are YAML, and you don't need to worry about checking that something can be parsed by the YAML parser - there are other ways to do that. The main concern is missing mappings or other missing values, or mappings which need a scalar of one type but have something else.

**Comment by pnorman** [comment]
fwiw, my use-case for scene file validation and style file validation in general is running continuous integration on the style.

**Comment by meetar** [comment]
Closing as out of scope.
