### ISSUE TITLE
Rework the tangram docs headings and topic structures

### ISSUE THREAD

**Issue by rmglennon** [tangrams/tangram-docs#67]
Currently, the Tangram help at https://mapzen.com/documentation/tangram/ has only two top-level entries in the TOC because everything is nested under "concept overviews" and "technical reference". Most of the titles are repeated between these headings (Filters in the overview, and filters in the API section), so it's not as easy as removing the top-level nodes. It would also get really redundant to put a word like "overview" in the first batch of headings or "API/parameter" in the second batch to distinguish them.

We also need to do need to do some work with the H2s and H3s in these topics to reduce the TOC subentries.

Original issue: https://github.com/mapzen/mapzen-docs-generator/issues/50

**Comment by meetar** [comment]
Propose splitting the technical documentation into three sections, all of which will live on the top level:
- scene file (common styling rules which comprise most of the current pages)
- JavaScript API
- Android SDK

This will separate the platform-specific pages from the rest of the docs, which will make the common rules more obvious, move a few things out of the technical docs, and allow the top level to do more work and expand to include future platform expansion.

We should also consider whether there's a better way to organize the pages w/r/t the sidebar, especially inside the scene file docs.

**Comment by meetar** [comment]
The current structure of this repo dates from when it only documented the scene file itself. So "cameras", "lights", "material", "procedural", and "shaders", all contain scene files in support of example files inside "pages." The "src" and "css" directories contain files which likewise support the map-drawing html.

The "pages" directory contains both the "technical documentation", in which the elements of the scene file are enumerated and described, as well as the "overviews", which are high-level prose descriptions of the concepts involved in the use of the scene file.

The structure of this repo is currently tied to a couple of factors, the first being the configuration of the mkdocs process by which it is converted to the html which lives at https://mapzen.com/documentation/tangram/ . As I recall, that process has a few restrictions of its own but should mostly be able to support whatever structure we choose – @louh can say more about that. The second factor is the ongoing support of a number of legacy links, most notably the "tronish" style, which was linked to directly long ago, went viral, and continues to get external traffic, though much less these days.

We've restructured the docs before while taking both factors into account, and I believe we can do it again if it's deemed desirable.

cc @blair1618 @rmglennon @mjcunningham

**Comment by meetar** [comment]
And to respond to @rmglennon's questions (apart from those relating to the Android SDK, which I'll leave to others):

> Would someone working on mobile only expect to see content for JS (and vice versa)?

In general I believe people working on a specific API would only expect to see content for that specific API.

> Do we expect more users to use Tangram JS or Android/ES?

I don't know! Right now I'd say our sample size is too small to tell, and until one of the libraries _completely crushes the other in a terrifying display of cultural dominance_ we should treat them as equals.

> How much overlap is there in the contents of the JS and Android/ES documentation?

The API documentation will be completely different. The goal for the scene file is for it to be interoperable, so there shouldn't be any difference in the scene file documentation among platforms, with a small number of exceptions which so far we are handling inline (example: https://mapzen.com/documentation/tangram/draw/#transition). Ideally we will eliminate these as the libraries continue to synchronize, though it's reasonable to expect they will persist.

**Comment by rmglennon** [comment]
mkdocs, the code that's used to generate mapzen.com/documentation, is pretty flexible. The only requirement is that we need one index.md page to display on the landing page for documentation/tangram. You can build top-level headings and hierarchy using different indents in the mkdocs configuration files. I _think_ it works for the md files to be in different folders within a repository.

I believe the headings may be the main "restructuring" to do, which is a matter of formatting the number of #s used in a page. For simplicity, we should have no more than two levels under a top heading in the TOC, and only a short list of headings so readers don't have to scroll so much. What shows up in the TOC is based on the #s in the markdown. Best to start with # for the title, then use ## and ### (I believe it's technically by number, so if you start with ### for your heading, even #### will show up...but simplest to start with just one #). 

In light of all those legacy links, it might be worth doing something to separate the docs from the old demos (maybe that means rename this repo again to "tangram-demos" and then move the md files to a true tangram-docs location?). Many of the other big help systems have separate repos for documentation (eg, valhalla-docs, pelias-docs, etc.) and use the master branch. I know here gh-pages is being used as the "master" so it can power the websites for the legacy demos.

**Comment by meetar** [comment]
Per meeting today: proposal is accepted, implementation to follow :) – I'll do a draft reorg in a test branch and link to the precog here when ready.

**Comment by meetar** [comment]
So precog isn't working because the CircleCI checks are failing because the "mapzen-docs-generator/meetar/tangram-reorg" branch refers to pages which are on the unmerged "tangram-docs/reorg" branch.

I suppose the worst case is we just get all the content ready as best we can, then merge them both at an off-peak time and fix any problems that arise ad hoc. (Or just merge "tangram/reorg" and check the precog then.)

**Comment by migurski** [comment]
I bet I can help with this, if you are able to explain it a little more?

**Comment by meetar** [comment]
Sure, though it's by no means urgent – I'm reorganizing the Tangram docs structure, and in the process adding and renaming files, and updating the config yamls on `mapzen-docs-generator`. When CircleCI runs, it breaks saying that there are references to missing pages. The pages exist, but they're in a new, unmerged branch on ths repo.

I'm guessing that when mk-docs it runs its conversions, it refers to the `gh-pages` branch of the repo in question. But I'm working with new branches on both the `mapzen-docs-generator` _and_ `tangram-docs` repos, and adding references in the one to newly-created pages in the other.

So unless I merge the `tangram-docs` changes, the `mapzen-docs-generator` won't be able to find them. But if I do merge them, that will also break the docs, because the old config files refer to the old file names and structure. So assuming I'm right about the mk-docs setup, unless we can change the branch that mk-docs is referencing, we can't get precog working to properly verify the changes.

Luckily this isn't a particularly high-stakes situation, and it's probably fine to just make the changes and fix anything that breaks ~live~. 🎸

**Comment by meetar** [comment]
Resolved with https://github.com/tangrams/tangram-docs/pull/86
~git solo~ 🎸
